name: Build XLibre Debian

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        include:
          - osimage: debian:stable
            osarchname: amd64
            osdistroname: debian
            runsonos: ubuntu-24.04
          - osimage: ubuntu:noble
            osarchname: amd64
            osdistroname: ubuntu
            runsonos: ubuntu-24.04
          - osimage: debian:stable
            osarchname: arm64
            osdistroname: debian
            runsonos: ubuntu-24.04-arm
          - osimage: ubuntu:noble
            osarchname: arm64
            osdistroname: ubuntu
            runsonos: ubuntu-24.04-arm
        # osimage: [debian:stable, ubuntu:noble]
        # runsonos: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ubuntu-latest
    container:
      image: debian:stable
    
    steps:
      - name: Install basic dependencies
        run: |
          apt-get update
          apt-get install -y git git-buildpackage devscripts debhelper build-essential equivs pristine-tar

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure git
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Build
        run: |
          make actions

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.osdistroname }}-packages-${{ matrix.osarchname }}
          path: build/
          if-no-files-found: warn
